[package]
cairo-version = "2.12.2"
name = "tamagotchi"
version = "0.1.0"
edition = "2023_11"

[cairo]
sierra-replace-ids = true

[scripts]
sepolia = "sozo -P sepolia clean && sozo -P sepolia build && sozo -P sepolia migrate --account-address $DEPLOYER_ACCOUNT_ADDRESS --private-key $DEPLOYER_PRIVATE_KEY"
mainnet = "sozo -P mainnet clean && sozo -P mainnet build && sozo -P mainnet migrate --account-address $DEPLOYER_ACCOUNT_ADDRESS --private-key $DEPLOYER_PRIVATE_KEY"

[dependencies]
starknet = "2.12.2"
dojo = "1.7.0"
dojo_cairo_macros = "1.7.0"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "2.12.2"
dojo_cairo_test = "1.7.0"

[profile.mainnet]
[profile.sepolia]
[profile.slot]
